In [98]:
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.datasets import load_iris

In [99]:
iris = load_iris()
print(dir(iris))
print()
print(iris.feature_names)
print()
print(iris.target)
print(iris.target_names)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [100]:
df1 = pd.DataFrame(iris.data, columns = iris.feature_names)

df2 = pd.DataFrame(iris.target)

df1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [101]:
df2

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [102]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df1, df2, random_state=10, test_size=0.2)

print(len(x_train),len(x_test),len(y_train),len(y_test))

120 30 120 30


In [103]:
from sklearn.svm import SVC

model_svc = SVC()

model_svc.fit(x_train, y_train)

/opt/anaconda3/envs/ML_Test/lib/python3.12/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [104]:
y_predicted_svc = modelsvc.predict(x_test)
print(y_predicted_svc)
modelsvc.score(x_test, y_test)

[1 2 0 1 0 1 2 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2]


0.9666666666666667

In [105]:
from sklearn.linear_model import LogisticRegression
model_logreg = LogisticRegression()

model_logreg.fit(x_train, y_train)

/opt/anaconda3/envs/ML_Test/lib/python3.12/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [106]:
y_predicted_logreg = modellogreg.predict(x_test)
print(y_predicted_logreg)
modellogreg.score(x_test, y_test)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2]


1.0

In [107]:
#confusion matrix (Support Vector Machine)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_predicted_svc, y_test)

cm

array([[10,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  7]])

In [108]:
#confusion matrix (Logistic Regression)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_predicted_logreg, y_test)

cm

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  7]])

In [109]:
#Decision Tree

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [110]:
y_predicted_tree = tree.predict(x_test)
print(y_predicted_tree)

tree.score(x_test, y_test)

[1 2 0 1 0 1 2 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2]


0.9666666666666667

In [111]:
#confusion matrix (Decision Tree)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_predicted_logreg, y_test)

cm

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  7]])

In [125]:
#Linear Regression (can't be used its classification problem)

from sklearn.linear_model import LinearRegression

linreg = LinearRegression()

linreg.fit(x_train, y_train)

LinearRegression()

In [127]:
import numpy as np

y_predicted_linreg = linreg.predict(x_test)
print(y_predicted_linreg)

linreg.score(x_test, y_test)

[[ 1.19103064]
 [ 1.74174147]
 [-0.10144906]
 [ 1.32601742]
 [-0.06325877]
 [ 0.98180908]
 [ 1.43935666]
 [ 1.02666812]
 [-0.05026778]
 [ 1.3120715 ]
 [ 1.42616689]
 [ 1.77779766]
 [ 1.199037  ]
 [-0.04413049]
 [-0.0043351 ]
 [ 1.83477326]
 [ 1.40799354]
 [ 0.00595062]
 [ 0.04676719]
 [-0.1223277 ]
 [ 1.90689943]
 [ 1.98106692]
 [ 1.57243507]
 [ 0.11801745]
 [ 1.2879331 ]
 [-0.04419675]
 [ 1.16978101]
 [ 1.26607257]
 [ 1.27600256]
 [ 2.09294878]]


0.9115961491141747

In [114]:
#confusion matrix (Linear Regression)
'''
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_predicted_linreg, y_test)

cm '''

'\nfrom sklearn.metrics import confusion_matrix\n\ncm = confusion_matrix(y_predicted_linreg, y_test)\n\ncm '

In [115]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators= 1) #n_estimators no. of decision trees

rf.fit(x_train, y_train)

/opt/anaconda3/envs/ML_Test/lib/python3.12/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=1)

In [116]:
y_predicted_rf = rf.predict(x_test)
print(y_predicted_rf)

rf.score(x_test, y_test)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2]


1.0

In [117]:
#confusion matrix (Linear Regression)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_predicted_rf, y_test)

cm

array([[10,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  7]])